# Site settings
title: Elvio Dev
description: Página pessoal de um desenvolvedor de Software

# User settings
username: Elvio Gomes
user_description: Programador com maior interesse em desenvolvimento web e mobile e um pouquinho de design. Estuda temas relacionados à Bioinformática, Inteligência artificial e Jogos Digitais. Nas horas vagas lê e assiste muita coisa da cultura pop, nerd e geek em geral.
user_title: Software Developer
email: elviobg@gmail.com
twitter_username: elviobg
github_username:  elviobg
gplus_username:  elviobg

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
